server:
  port: 8008

spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    #druid:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://129.211.22.72:3306/hostpital?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&failOverReadOnly=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
#    url: jdbc:mysql://rm-bp1saig5x0v06rmeoco.mariadb.rds.aliyuncs.com:3306/xbkj?useUnicode=true&allowMultiQueries=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&failOverReadOnly=false&serverTimezone=Asia/Shanghai
#    username: vitcloud
#    password: Xbkj20190125@

  # 配置初始化大小、最小、最大
    initial-size: 5
    min-idle: 1
    max-active: 50
    #配置获取连接等待超时的时间
    max-wait: 30000
    #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    time-between-eviction-runs-millis: 60000
    #配置一个连接在池中最小生存的时间，单位是毫秒
    min-evictable-idle-time-millis: 300000
    #测试连接
    validation-query: SELECT 'x'
    #申请连接的时候检测，建议配置为true，不影响性能，并且保证安全性
    test-while-idle: true
    #获取连接时执行检测，建议关闭，影响性能
    test-on-borrow: false
    #归还连接时执行检测，建议关闭，影响性能
    test-on-return: false
    #是否开启PSCache，PSCache对支持游标的数据库性能提升巨大，oracle建议开启，mysql下建议关闭
    pool-prepared-statements: false
    #开启poolPreparedStatements后生效
    max-pool-prepared-statement-per-connection-size: 20
    #配置扩展插件，常用的插件有=>stat:监控统计  log4j:日志  wall:防御sql注入
    filters: stat,wall
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # Druid WebStatFilter配置
    web-stat-filter:
      enabled: true
      url-pattern: /*
      exclusions: '*.gif,*.png,*.jpg,*.html,*.adminlte,*.css,*.ico,/druid/*'
    # 打印sql
    logging:
      level:
        com.xbkj.cloud.permission.mapper.user: DEBUG


mybatis-plus:
  #  type-aliases-package: com.xbkj.cloud.base.core.model
  mapper-locations:  classpath*:mapper/*.xml
  configuration:
    # resultMap返回null字段
    map-underscore-to-camel-case: true
    return-instance-for-empty-row: true
    call-setters-on-nulls: true
    #    global-config:
    #      db-config:
    #        id-type: auto
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
